apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-rain-clustering-schedule
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: True
          containers:
            - name: k8s-rain-clustering
              image: [your image from dockerhub]
              env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: k8s-api-key
                      key: api_key.txt
                - name: API_TWILIO_SID
                  valueFrom:
                    secretKeyRef:
                      name: k8s-api-twilio-sid
                      key: api_twilio_sid.txt
                - name: API_TWILIO_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: k8s-api-twilio-token
                      key: api_twilio_token.txt
                - name: API_TWILIO_NUM
                  valueFrom:
                    secretKeyRef:
                      name: k8s-api-twilio-num
                      key: api_tel_num.txt
                - name: SQL_SERVER_HOST
                  value: host.docker.internal
                - name: SQL_SERVER_PORT
                  value: [your sql port]
                - name: SQL_SERVER_USERNAME
                  value: [your sql username]
                - name: SQL_SERVER_PASSWORD
                  value: [your sql password]
                - name: SQL_SERVER_DATABASE
                  value: [your sql database]
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 4025
          imagePullSecrets:
            - name: k8s-registry-secret
          restartPolicy: Never